import type { Metadata } from "next";
import LegalPage, { LegalSection } from "@/components/ui/LegalPage";

export const metadata: Metadata = {
  title: "Privacy Policy — RegGames",
};

export default function PrivacyPageEn() {
  return (
    <LegalPage title="Privacy Policy" updated="July 5, 2026" locale="en">
      <LegalSection title="Introduction">
        <p>
          RegGames is a software developer building mobile apps and games. All apps offered by RegGames are provided free of charge.
        </p>
        <p>
          This page informs users of apps developed by RegGames of our policies regarding the collection, use, and disclosure of information.
        </p>
      </LegalSection>

      <LegalSection title="Information Collection and Use">
        <p>RegGames apps do not directly collect personal information such as your name, email address, or precise location data.</p>
        <p>
          However, to improve user experience, provide leaderboard services, collect analytics, and send notifications, we rely on the third-party services below. These services may collect some technical data.
        </p>
      </LegalSection>

      <LegalSection title="Third-Party Services">
        <div>
          <h3 className="font-heading font-semibold text-white text-base mb-1.5">1. Unity LevelPlay (ironSource) — Ad Platform</h3>
          <p>
            Used for ad delivery and analytics. Device information, IP address, advertising identifiers, and usage data may be collected. Privacy policy:{" "}
            <a href="https://unity.com/legal/privacy-policy" target="_blank" rel="noopener noreferrer" className="text-primary">
              unity.com/legal/privacy-policy
            </a>
          </p>
        </div>

        <div>
          <h3 className="font-heading font-semibold text-white text-base mb-1.5">2. Google Play Services</h3>
          <p>
            Privacy policy:{" "}
            <a href="https://policies.google.com/privacy" target="_blank" rel="noopener noreferrer" className="text-primary">
              policies.google.com/privacy
            </a>
          </p>
        </div>

        <div>
          <h3 className="font-heading font-semibold text-white text-base mb-1.5">3. Firebase Firestore — Player Data Sync</h3>
          <p>
            Game data is synced to Firebase Firestore via a device-based anonymous identifier (<code>SystemInfo.deviceUniqueIdentifier</code>). The data stored includes:
          </p>
          <ul className="list-disc pl-5 flex flex-col gap-1.5">
            <li>Anonymous device identifier</li>
            <li>User-chosen display name</li>
            <li>Coin and Gem balances</li>
            <li>Purchased content and selected character/outfit</li>
            <li>Feature upgrade levels (Shield, Jump)</li>
            <li>Best score and distance</li>
            <li>Daily reward status</li>
            <li>Game session data: score, distance, coins earned, date/time, app version</li>
            <li>Account first-seen and last-seen timestamps</li>
          </ul>
          <p>
            This data is used solely to preserve game progress and for developer analytics; it is not shared with third parties. Firebase privacy policy:{" "}
            <a href="https://firebase.google.com/support/privacy" target="_blank" rel="noopener noreferrer" className="text-primary">
              firebase.google.com/support/privacy
            </a>
          </p>
        </div>

        <div>
          <h3 className="font-heading font-semibold text-white text-base mb-1.5">4. Firebase Cloud Messaging (FCM) — Push Notifications</h3>
          <p>
            Used to send in-game notifications. A topic subscription is created based on the user&apos;s language preference (Turkish/English). Notification permission is requested by the app; users may decline it or disable it later in settings. Firebase privacy policy:{" "}
            <a href="https://firebase.google.com/support/privacy" target="_blank" rel="noopener noreferrer" className="text-primary">
              firebase.google.com/support/privacy
            </a>
          </p>
        </div>

        <div>
          <h3 className="font-heading font-semibold text-white text-base mb-1.5">5. Unity Gaming Services (UGS) — Leaderboards</h3>
          <p>
            Unity Gaming Services powers the leaderboard feature. Sign-in is anonymous (no email or password required). The following data is processed:
          </p>
          <ul className="list-disc pl-5 flex flex-col gap-1.5">
            <li>Anonymous player ID (generated by UGS)</li>
            <li>User-chosen display name (up to 12 characters)</li>
            <li>End-of-run score data (weekly, monthly, and all-time leaderboards)</li>
            <li>Selected character/outfit (for avatar display on the leaderboard)</li>
          </ul>
          <p>
            UGS privacy policy:{" "}
            <a href="https://unity.com/legal/privacy-policy" target="_blank" rel="noopener noreferrer" className="text-primary">
              unity.com/legal/privacy-policy
            </a>
          </p>
        </div>
      </LegalSection>

      <LegalSection title="Data Deletion Requests">
        <p>
          Users can permanently delete their leaderboard account and related UGS data using the &quot;Delete Account&quot; option in the in-game Settings menu. This action cannot be undone.
        </p>
        <p>
          To request deletion of anonymous device data stored in Firebase Firestore, contact us at{" "}
          <a href="mailto:reggamesstudio@gmail.com" className="text-primary">
            reggamesstudio@gmail.com
          </a>
          .
        </p>
        <p>For data collected by third-party service providers, please use that provider&apos;s own privacy policy and tools.</p>
      </LegalSection>

      <LegalSection title="Changes to This Privacy Policy">
        <p>This policy may be updated from time to time. Changes will be posted on this page.</p>
      </LegalSection>

      <LegalSection title="Contact">
        <p>
          <a href="mailto:reggamesstudio@gmail.com" className="text-primary">
            reggamesstudio@gmail.com
          </a>
        </p>
      </LegalSection>
    </LegalPage>
  );
}
